name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: dotnet test
      working-directory: ./samples/dotnetapp/test
      run: dotnet test
    - name: Build with dotnet
      working-directory: ./samples/dotnetapp
      run: dotnet build --configuration Release
