name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: dotnet test
      working-directory: ./samples/dotnetapp/tests
      run: dotnet test
    - name: Build with dotnet
      working-directory: ./samples/dotnetapp
      run: dotnet build --configuration Release
    - name: dotnet-sonarscanner
      uses: Secbyte/dotnet-sonarscanner@2.0
      with:
        # Command to invoke build
        buildCommand: dotnet build
        # Command to invoke tests
        testCommand:  dotnet test
        # Specifies the key of the analyzed project in SonarQube
        projectKey: dotnettest
        # Specifies the name of the analyzed project in SonarQube
        projectName: dotnettest
        # The server URL
        sonarHostname: https://sonarcloud.io
        # Organisation
        sonarOrganisation: raknas999 
        # Arguments to append to the begin command
        beginArguments: # optional
        # Arguments to append to the end command
        endArguments: # optional
